### ISSUE TITLE
Could not find SED module with pip install

### ISSUE THREAD

**Issue by yuxuanpang** [arnauqb/qsosed#1]
Hi, I install the package by pip install pyagn, it seems success and could import pyagn as well. But when I test your example, it seems that could not load SED from pyagn package "ImportError: cannot import name 'SED' from 'pyagn' ".
I also try to download the package in github, but there exists anther error when I use the commmend "python setup.py install", it says "Project name qsosed was given, but was not able to be found".

**Comment by arnauqb** [comment]
Hi @yuxuanpang, sorry for the late reply, I have not maintained this package for a while so I'd advise you to use it with caution.

Could you try installing it this way?

```
git clone git@github.com:arnauqb/qsosed.git
cd qsosed
python setup.py install
```
then this should work

```python
from qsosed.sed import SED
sed = SED()
```

Cheers
